### ISSUE TITLE
Question about negative samples and inversion sampling

### ISSUE THREAD

**Issue by hengseuer** [surfemb/surfemb.github.io#4]
Thank you for your previous reply.  I have a few more questions.

1. During training, for each object, whether the negative sample remains the same or is randomly sampled for each iterate?

2. When a positive sample and a negative sample are very close, will the corresponding loss be calculated?

3. In the stage of Sampling Pose Hypotheses, four pairs of 2d-3d  correspondence are sampled from R<sup>HxWX|S|</sup>, and a pose hypothesis can be found by AP3P, this process is iterated 20.000 times, right?

**Comment by rasmushaugaard** [comment]
The code is now available at https://github.com/rasmushaugaard/surfemb
Feel free to open an issue there, if needed :)
