### ISSUE TITLE
About P.E. setting

### ISSUE THREAD

**Issue by shanice-l** [surfemb/surfemb.github.io#5]
Hi, authors!

Thank you for your inspiring work. 

I'm wondering whether you train one neural network per instance or a universal network for all instances. If it is under the first situation, have you ever tested the generalizability of surfEmb cross instances? It's an interesting direction to explore, and as we know LatentFusion is able to fulfil this.

Looking forward to your reply.

**Comment by rasmushaugaard** [comment]
Hi

We have tried only having a single object-specific layer in the query decoder, but obtain better results with completely separate decoders.

We have not however explored actually sharing an embedding space across objects.
One way to share the embedding space could be to have one query model and separate key models.
If you want to generalize to unseen objects, a different key model architecture is probably needed, but yeah, it would be an interesting direction.
The code is now available at https://github.com/rasmushaugaard/surfemb , so you can give it a try if you want :)

BR Rasmus
